version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/endpoint"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/credential"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/services/s3"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/services/bos"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/services/cos"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/services/dropbox"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/services/ftp"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/services/gcs"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/services/gdrive"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/services/hdfs"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/services/ipfs"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/services/kodo"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/services/memory"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/services/minio"
    schedule:
      interval: daily
