[append-offset]
type = "int64"
description = "AppendOffset is the offset of the append object."

[content-length]
type = "int64"

[content-md5]
type = "string"

[content-type]
type = "string"

[etag]
type = "string"

[id]
type = "string"
export = true
description = "ID is the unique key in storage."

[last-modified]
type = "time.Time"

[link-target]
type = "string"
description = "LinkTarget is the symlink target for link object."

[mode]
type = "ObjectMode"
export = true

[multipart-id]
type = "string"
description = "MultipartID is the part id of part object."

[path]
type = "string"
export = true
description = "Path is either the absolute path or the relative path towards storage's WorkDir depends on user's input."

[system-metadata]
type = "interface{}"
description = "SystemMetadata stores system defined metadata."

[user-metadata]
type = "map[string]string"
description = "UserMetadata stores user defined metadata."
