[append-offset]
type = "int64"
description = "AppendOffset is the offset of the append object."

[content-disposition]
type = "string"

[content-length]
type = "int64"

[content-md5]
type = "string"

[content-type]
type = "string"

[etag]
type = "string"

[id]
type = "string"
export = true
description = """
ID is the unique key in storage.

ID SHOULD be an absolute path compatible with the target operating system-defined file paths, or a unique identifier specified by service.
"""

[last-modified]
package = "time"
type = "Time"

[link-target]
type = "string"
description = "LinkTarget is the symlink target for link object."

[mode]
type = "ObjectMode"
export = true

[multipart-id]
type = "string"
description = "MultipartID is the part id of part object."

[path]
type = "string"
export = true
description = """
Path is either the absolute path or the relative path towards storage's WorkDir depends on user's input.

Path SHOULD be Unix style.
"""

[system-metadata]
type = "interface{}"
description = "SystemMetadata stores system defined metadata."

[user-metadata]
type = "map[string]string"
description = "UserMetadata stores user defined metadata."
