name: "Services Test Kodo"

on:
   push:
     paths:
       - 'services/kodo/**'
   pull_request:
     paths:
       - 'services/kodo/**'

jobs:
  services_test_kodo:
    name: "Services Test Kodo"
    runs-on: self-hosted

    strategy:
      matrix:
        go: [ "1.15", "1.16" ]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Load secret
        uses: 1password/load-secrets-action@v1
        env:
          STORAGE_KODO_CREDENTIAL: op://Engineering/Kodo/testing/credential
          STORAGE_KODO_NAME: op://Engineering/Kodo/testing/name
          STORAGE_KODO_ENDPOINT: op://Engineering/Kodo/testing/endpoint

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        env:
          STORAGE_BOS_INTEGRATION_TEST: on
        working-directory: services/kodo
        run: make integration_test
