name: "Services Test Memory"

concurrency:
  group: ${{ github.action }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  push:
    paths:
      - 'services/memory/**'
  pull_request:
    paths:
      - 'services/memory/**'

jobs:
  unit_test:
    name: Unit Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go: [ "1.16", "1.17" ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Test
        working-directory: services/memory
        run: make integration_test
