name: "Services Test Cos"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  push:
    paths:
      - 'services/cos/**'
  pull_request:
    paths:
      - 'services/cos/**'

jobs:
  services_test_cos:
    name: "Services Test Cos"
    runs-on: self-hosted

    strategy:
      matrix:
        go: [ "1.16", "1.17" ]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Load secret
        uses: 1password/load-secrets-action@v1
        env:
          STORAGE_COS_CREDENTIAL: op://Engineering/Cos/testing/credential
          STORAGE_COS_NAME: op://Engineering/Cos/testing/name
          STORAGE_COS_LOCATION: op://Engineering/Cos/testing/location

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        env:
          STORAGE_COS_INTEGRATION_TEST: on
        working-directory: services/cos
        run: make integration_test
