name: "Services Test Azblob"

concurrency:
  group: ${{ github.action }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
   push:
     paths:
       - 'services/azblob/**'
   pull_request:
     paths:
       - 'services/azblob/**'

jobs:
  services_test_azblob:
    name: "Services Test Azblob"
    runs-on: self-hosted

    strategy:
      matrix:
        go: [ "1.16", "1.17" ]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Load secret
        uses: 1password/load-secrets-action@v1
        env:
          STORAGE_AZBLOB_CREDENTIAL: op://Engineering/Azblob/testing/credential
          STORAGE_AZBLOB_NAME: op://Engineering/Azblob/testing/name
          STORAGE_AZBLOB_ENDPOINT: op://Engineering/Azblob/testing/endpoint

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        env:
          STORAGE_AZBLOB_INTEGRATION_TEST: on
        working-directory: services/azblob
        run: make integration_test
