name: "Services Test Ftp"

concurrency:
  group: ${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  push:
    paths:
      - 'services/ftp/**'
  pull_request:
    paths:
      - 'services/ftp/**'

jobs:
  integration_test_1:
    name: Service Test on fclairamb/ftpserver
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ "1.16", "1.17" ]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download ftpserver release
        uses: robinraju/release-downloader@v1.2
        with:
          repository: fclairamb/ftpserver
          tag: v0.10.0
          fileName: ftpserver-linux-amd64
          out-file-path: services/ftp/tests/fclairamb-ftpserver

      - name: Start ftp server
        working-directory: services/ftp/tests/fclairamb-ftpserver
        run: |
          mkdir data
          chmod +x ftpserver-linux-amd64
          ./ftpserver-linux-amd64 &

      - name: Build
        working-directory: services/ftp
        run: make build

      - name: Integration Test
        working-directory: services/ftp
        env:
          STORAGE_FTP_INTEGRATION_TEST: on
          STORAGE_FTP_CREDENTIAL: basic:user:password
          STORAGE_FTP_ENDPOINT: tcp:127.0.0.1:2121
        run: make integration_test

  integration_test_2:
    name: Service Test on vsftpd
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ "1.16", "1.17" ]
        os: [ ubuntu-latest ]

    services:
      ftp:
        image: fauria/vsftpd
        ports:
          - 2121:21
          - 21000-22000:21000-22000
        env:
          FTP_USER: admin
          FTP_PASS: admin
          PASV_ADDRESS: 127.0.0.1
          PASV_MIN_PORT: 21000
          PASV_MAX_PORT: 22000
        volumes:
          - vsftpd-data:/home/vsftpd

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Integration Test
        working-directory: services/ftp
        env:
          STORAGE_FTP_INTEGRATION_TEST: on
          STORAGE_FTP_CREDENTIAL: basic:admin:admin
          STORAGE_FTP_ENDPOINT: tcp:127.0.0.1:2121
        run: make integration_test
