name: "Services Test Minio"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  push:
    paths:
      - 'services/minio/**'
  pull_request:
    paths:
      - 'services/minio/**'

jobs:
  integration_test:
    name: "Integration Test"
    runs-on: ubuntu-latest

    services:
      minio:
        image: wktk/minio-server
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: "minioadmin"
          MINIO_SECRET_KEY: "minioadmin"

    strategy:
      matrix:
        go: [ "1.16", "1.17" ]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        env:
          STORAGE_MINIO_INTEGRATION_TEST: "on"
          STORAGE_MINIO_CREDENTIAL: "hmac:minioadmin:minioadmin"
          STORAGE_MINIO_NAME: "test-bucket"
          STORAGE_MINIO_ENDPOINT: "http:127.0.0.1:9000"
        working-directory: services/minio
        run: make integration_test
