name: "Services Test S3"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  push:
    paths:
      - 'services/s3/**'
    tags-ignore:
      - '**'
    branches:
      - '**'
  pull_request:
    paths:
      - 'services/s3/**'

jobs:
  services_test_s3:
    name: "Services Test S3"
    runs-on: self-hosted

    strategy:
      matrix:
        go: [ "1.16", "1.17" ]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Load secret
        uses: 1password/load-secrets-action@v1
        env:
          STORAGE_S3_CREDENTIAL: op://Engineering/S3/testing/credential
          STORAGE_S3_NAME: op://Engineering/S3/testing/name
          STORAGE_S3_LOCATION: op://Engineering/S3/testing/location

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        env:
          STORAGE_S3_INTEGRATION_TEST: on
        working-directory: services/s3
        run: make integration_test

  service_test_minio:
    name: "Service Test Minio"
    runs-on: ubuntu-latest

    services:
      minio:
        image: wktk/minio-server
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: "minioadmin"
          MINIO_SECRET_KEY: "minioadmin"

    strategy:
      matrix:
        go: [ "1.16", "1.17" ]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        env:
          STORAGE_S3_INTEGRATION_TEST: "on"
          STORAGE_S3_CREDENTIAL: "hmac:minioadmin:minioadmin"
          STORAGE_S3_NAME: "test-bucket"
          STORAGE_S3_ENDPOINT: "http:127.0.0.1:9000"
          STORAGE_S3_LOCATION: "local"
        working-directory: services/s3
        run: make integration_test
