name: "Services Test Fs"

concurrency:
  group: ${{ github.action }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  push:
    paths:
      - 'services/fs/**'
  pull_request:
    paths:
      - 'services/fs/**'

jobs:
  integration_test:
    name: "Integration Test"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go: [ "1.16", "1.17" ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        env:
          STORAGE_FS_INTEGRATION_TEST: on
        run: make integration_test
